name: Deploy to EC2

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host ec2-instance
                HostName ${{ secrets.EC2_HOST }}
                User ${{ secrets.EC2_USER }}
                IdentityFile ~/.ssh/id_rsa
                StrictHostKeyChecking no" > ~/.ssh/config

      - name: Deploy application
        run: |
          ssh ec2-instance << 'EOF'
          cd ~/ichgram/media
          git checkout production
          git pull origin production
          sudo docker-compose down
          sudo docker-compose up -d --build
          EOF